connection:
  localhost: 

modules:
  transport_type: 
  encryptor_type: 
  framer_type: 
  dispatcher_type: 
  auth_type: 

logs:
  log_level: 

secure:
  key_32_bytes: 

admin:
  adminhost: 
  authentication: 
  user: 
  password: 